youtubeProject/Youtube/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns=[
    path('',views.home,name='home'),
    path('login/',views.login_view,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout_view,name='logout'),
    path('upload/',views.upload,name='upload'),
    path('video/<int:video_id>/',views.video_view,name='video_view'),
    path('liked_videos/',views.liked_videos,name="liked_videos"),
    path('trending/',views.trending,name="trending"),
    path('subscriptions/',views.subscriptions,name='subscriptions'),
    path('channel/<str:name>',views.channel,name='channel'),
    path('editProfile/',views.edit_profile,name='edit_profile'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

youtubeProject/youtubeProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Youtube.urls')),
]

youtubeProject/Youtube/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile/', blank=True)
    background_img=models.ImageField(upload_to='bg-images/',blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    
    def __str__(self):
        return f'{self.user}'
    
    def users_subscribed(self):
       return Profile.objects.filter(subscriber__channel=self)
   
    def users_subscribed_cnt(self):
       return self.users_subscribed().count()
    def get_channels_subscribed(self):
        a= Subscribers.objects.filter(user=self)
        x=[]
        for b in a:
            # print((b.channel.user))
            x.append((b.channel.user.id))
        # print(x)
        return x
        
    
class Subscribers(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='subscriber')
    channel = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='channel')
    
    class Meta:
        unique_together=[
            ('channel','user'),
        ]

class Video(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=False)
    description = models.TextField()
    video_file = models.FileField(upload_to='videos/', blank=False)
    thumbnail = models.ImageField(upload_to='thumbnails/')
    likes=models.IntegerField(default=0)
    views=models.IntegerField(default=0)
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Video: {self.title} :- {self.user}"
    
    def user_has_liked(self):
        # print(User.objects.filter(videolikes__video=self))
        
        return User.objects.filter(videolikes__video=self)
    
class VideoLikes(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    
    class Meta:
        unique_together=[
            ('video','user'),
        ]
        
class Comments(models.Model):
    commenter = models.ForeignKey(User,on_delete=models.CASCADE)
    video = models.ForeignKey(Video,on_delete=models.CASCADE)
    text = models.CharField(max_length=250)
    date_posted = models.DateTimeField(auto_now_add=True)
    likes=models.IntegerField(default=0)
    replies_cnt=models.IntegerField(default=0)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    
    class Meta:
        ordering=[
            '-date_posted'
        ]
    
    def __str__(self):
        return self.text[:15] + "..."
    
    def users_liked(self):
        # print('ok ',User.objects.filter(commentlikes__liked_comment=self))
        return User.objects.filter(commentlikes__liked_comment=self)

class CommentLikes(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    liked_comment = models.ForeignKey(Comments, on_delete=models.CASCADE)
    
    class Meta:
        unique_together=[
            ('liked_comment','user'),
        ]

youtubeProject/Youtube/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Video, Comments, Profile

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

class VideoUploadForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title','description','video_file','thumbnail']
        widgets = {
            'video_file': forms.FileInput(attrs={'accept': 'video/mp4'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comments
        fields = ['text']
        widgets = {
            'text': forms.TextInput(attrs={'placeholder':'Add a comment...'}),
        }
        
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=[
            'background_img','image','bio'
        ]

youtubeProject/Youtube/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegistrationForm, VideoUploadForm, CommentForm, ProfileEditForm
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Profile, Video, VideoLikes, Comments, CommentLikes, Subscribers


# Create your views here.

def home(request):
    user = request.user
    all_videos = Video.objects.all().order_by('-upload_date')
    return render(request, 'home.html', {'user': user, 'videos': all_videos})


def register(request):
    if (request.user.is_authenticated):
        return redirect('home')
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('home')
    else:
        form = RegistrationForm()

    return render(request, 'register.html', {'form': form})


def login_view(request):
    if (request.user.is_authenticated):
        return redirect('home')
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')

@login_required
def edit_profile(request):
    print('ok')
    if request.method == 'POST':
        form = ProfileEditForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('channel',name=request.user.username)  # Redirect to the user's profile page
    else:
        form = ProfileEditForm(instance=request.user.profile)
    
    return render(request, 'edit_profile.html', {'form': form})


@login_required(login_url='/login/')
def upload(request):
    if request.method == 'POST':
        form = VideoUploadForm(request.POST, request.FILES)
        if form.is_valid():
            video = form.save(commit=False)
            video.user = request.user
            video.save()
            return redirect('home')
    else:
        form = VideoUploadForm()

    return render(request, 'upload_video.html', {'form': form})

@login_required(login_url='/login/')
def liked_videos(request):
    liked=VideoLikes.objects.filter(user=request.user)
    liked_videos=[]
    for video in liked:
        liked_videos.append(video.video)
    context={
        'liked_videos':liked_videos,
    }
    return render(request,'liked_videos.html',context)
@login_required(login_url='/login/')
def subscriptions(request):
    
    # print(request.user.profile)
    current_profile=(request.user.profile)
    # print('ok')
    channel_id=current_profile.get_channels_subscribed()
    # print(channel_id)
    # print(Profile.objects.filter(channel__subscriber=request.user.profile))
    uploaded_videos = Video.objects.filter(user_id__in=channel_id)
    # print(uploaded_videos)
    context={
        'videos':uploaded_videos
    }
    return render(request,'subscriptions.html',context)

def trending(request):
    trending_videos=Video.objects.all().order_by('-views')
    context={
        'videos':trending_videos
    }
    return render(request,'trending.html',context)

def channel(request,name):
    channel=User.objects.get(username=name)
    channel_videos=Video.objects.filter(user=channel)
    
    if request.method == "POST":
        input_type = request.POST.get('video_id')
        if (input_type== 'subscribe'):
                print('ok')
                subscribe_to = int(request.POST.get('subscribe'))
                # print(subscribe_to)
                user=channel
                # print(user)
                profile=Profile.objects.get(user=user)
                subscribed_users=(profile.users_subscribed())
                print(subscribed_users)
                if(request.user.profile in subscribed_users):
                    print('present')
                    Subscribers.objects.filter(user=request.user.profile,channel=profile).delete()
                    print('deleted')
                else:
                    print('not-present')
                    Subscribers.objects.create(user=request.user.profile,channel=profile)
                    print('created')
    context={
        'videos':channel_videos,
        'channel':channel,
    }
    return render(request,'channel_view.html',context)

def video_view(request, video_id):

    video = get_object_or_404(Video, pk=video_id)
    all_comments = Comments.objects.filter(video=video)
    video.views += 1
    video.save()
    comment_form = CommentForm(request.POST)

    videos = Video.objects.all()

    if request.user.is_authenticated:
        liked_video = VideoLikes.objects.filter(
            user=request.user, video=video_id).exists()

    if request.method == "POST" :
        if not request.user.is_authenticated:
            return redirect('login')
        input_type = request.POST.get('video_id')

        if (input_type == 'like' and not liked_video):
            print('liked')
            VideoLikes.objects.create(user=request.user, video=video)
            video.likes += 1
            video.views -= 2
            video.save()
            return redirect('video_view', video_id=video_id)

        if (input_type == 'like' and liked_video):
            print('unliked')
            video.likes -= 1
            video.views -= 2
            VideoLikes.objects.filter(user=request.user, video=video).delete()
            video.save()
            return redirect('video_view', video_id=video_id)

        if (input_type == 'new_comment'):
            if comment_form.is_valid():
                new_comment = Comments(
                    text=request.POST['text'], commenter=request.user, video=video)
                new_comment.save()
                video.views -= 1
                return redirect('video_view', video_id=video_id)

        if (input_type in ['com_like', 'com_dislike']):
            comment_id = int(request.POST.get('comment_id'))
            com = get_object_or_404(Comments, pk=comment_id)
            like_obj = CommentLikes.objects.filter(
                liked_comment=com, user=request.user).exists()
            if input_type == 'com_like':
                if like_obj:
                    com.likes -= 1
                    com.save()
                    CommentLikes.objects.filter(
                        liked_comment=com, user=request.user).delete()
                else:
                    com.likes += 1
                    com.save()
                    CommentLikes.objects.create(
                        liked_comment=com, user=request.user)
            else:
                if like_obj:
                    com.likes -= 1
                    com.save()
                    CommentLikes.objects.filter(
                        liked_comment=com, user=request.user).delete()
            return redirect('video_view', video_id=video_id)

        if (input_type == 'sub_comment'):
            if comment_form.is_valid():

                comment_id = int(request.POST.get('parent-com-id'))
                parent_comment = get_object_or_404(Comments, pk=comment_id)
                parent_comment.replies_cnt += 1
                parent_comment.save()
                Comments.objects.create(
                    text=request.POST['text'], commenter=request.user, video=video, parent_comment=parent_comment)
                return redirect('video_view', video_id=video_id)
        
        if (input_type== 'subscribe'):
            print('ok')
            subscribe_to = int(request.POST.get('subscribe'))
            # print(subscribe_to)
            user=User.objects.get(pk=subscribe_to)
            # print(user)
            profile=Profile.objects.get(user=user)
            subscribed_users=(profile.users_subscribed())
            print(subscribed_users)
            if(request.user.profile in subscribed_users):
                print('present')
                Subscribers.objects.filter(user=request.user.profile,channel=profile).delete()
                print('deleted')
            else:
                print('not-present')
                Subscribers.objects.create(user=request.user.profile,channel=profile)
                print('created')
            
        
    context = {
        'cur_video': video,
        'videos': videos,
        'comments': all_comments,
        'com_count': all_comments.count(),
        'com_form': comment_form,
        'current_url': request.build_absolute_uri(),
    }

    return render(request, 'video.html', context)

youtubeProject/Youtube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="icon" href="{% static 'pics/utube.ico' %}" type="image/x-icon" />
    <title>{% block title %} Title {% endblock title %}</title>

    {% block head %} {% endblock head %}
  </head>

  <body>
    <div class="header">
      <div class="header__left">
        <i id="menu" class="material-icons menu-icon">menu</i>
        <a href="{% url 'home' %}" title="YouTube">
          <img
            src="https://cdn.mos.cms.futurecdn.net/8gzcr6RpGStvZFA2qRt4v6.jpg"
            alt=""/>
          </a>
      </div>

      <div class="header__search">
        <form action="">
          <input type="text" placeholder="Search" />
          <button><i class="material-icons">search</i></button>
        </form>
      </div>

      <div class="header__icons">
        <i class="material-icons display-this search-icon">search</i>
        <a href="{% url 'upload' %}" title="Upload video">
          <i class="material-icons">video_call</i></a
        >
        <i class="material-icons">apps</i>
        <i class="material-icons">notifications</i>
        {% if user.is_authenticated %}
        <button class="profile-button" onclick=toggleMenu() >
          <img
            src="{% if user.profile.image %}{{ user.profile.image.url }}
              {% else %}
              {% static 'pics/blank-profile.png'%}
              {% endif %}"
            alt="Profile"
            class="profile-pic"
            title="{{user.username}}"
          />
          
          <ul class="menu-list" id="menuList">
            <li><a href="{% url 'channel' user.username%}">
                <div class="contain">
                    <i class="material-icons  menu-icons">person</i>
                    <span class="text">
                        My Account
                    </span>
                </div>
            </a></li>
            <li><a href="#">
                <div class="contain">
                    <i class="material-icons menu-icons">history</i>
                    <span class="text">
                        History
                    </span>
                </div>
            </a></li>
            <li><a href="{% url 'logout' %}">
                <div class="contain">
                    <i class="material-icons menu-icons">logout</i>
                    <span class="text">
                        Sign out
                    </span>
                </div>
            </a></li>
          </ul>
              
        </button>
        {% else %}
        <a href="{% url 'login' %}" title="Login/Register">
          <i class="material-icons display-this">account_circle</i>
        </a>
        {% endif %}
      </div>
    </div>
    <!-- Header Ends -->

    <!-- Main Body Starts -->
    <div class="mainBody">
      <!-- Sidebar Starts -->

      <div class="sidebar">
        <div class="sidebar__categories">
          <a href="{% url 'home' %}">
            <div class="sidebar__category">
              <i class="material-icons">home</i>
              <span class="icon-text">Home</span>
            </div>
          </a>
          <a href="{% url 'trending' %}">
            <div class="sidebar__category">
              <i class="material-icons">local_fire_department</i>
              <span class="icon-text">Trending</span>
            </div>
          </a>
          <a href="{% url 'subscriptions' %}">
            <div class="sidebar__category">
              <i class="material-icons">subscriptions</i>
              <span class="icon-text">Subcriptions</span>
            </div>
          </a>
        </div>
        <hr />
        <div class="sidebar__categories">

          
          {% if user.is_authenticated %}
            <a href="{% url 'channel' user.username %}">
              <div class="sidebar__category">
                <i class="material-icons">play_arrow</i>
                <span class="icon-text">Your Videos</span>
              </div>
            </a>
          {% else %}
            <a href="{% url 'login' %}">
              <div class="sidebar__category">
                <i class="material-icons">play_arrow</i>
                <span class="icon-text">Your Videos</span>
              </div>
            </a>
          {% endif %}
          <a href="{%url 'liked_videos'%}">
            <div class="sidebar__category">
              <i class="material-icons">thumb_up</i>
              <span class="icon-text">Liked Videos</span>
            </div>
          </a>
        </div>
        <hr />
      </div>
      <!-- Sidebar Ends -->

      <!-- Videos Section -->

      <div class="videos">{% block body %} ok{% endblock body %}</div>
    </div>
    <script>
      function toggleMenu() {
        var menu = document.getElementById("menuList");
        menu.style.display = menu.style.display === "block" ? "none" : "block";
      }
      document.addEventListener('mouseup', function (e) {
        var menuList = document.getElementById('menuList');
        var profileButton = document.querySelector('.profile-button');
    
        if (!menuList.contains(e.target) && !profileButton.contains(e.target)) {
            menuList.style.display = 'none';
        }
    });
      document.addEventListener("DOMContentLoaded", function () {
        const hamburgerIcon = document.getElementById("menu");
        const sidebar = document.querySelector(".sidebar");
        hamburgerIcon.addEventListener("click", function () {
          sidebar.classList.toggle("sidebar-visible");
        });
      });
      
    </script>
  </body>
</html>

youtubeProject/Youtube/templates/channel_view.html
{% extends 'trending.html' %}
{% load static %}

{% block title %}
    Youtube- {{channel.username}}
{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/channel.css' %}">
{% endblock head %}


{% block heading %}
    <div class="heading">
        {% if channel.profile.background_img %}
        <img loading="lazy" src="{{ channel.profile.background_img.url }}" alt="" class="background">
        {% endif %}
        <div class="channel-details">
            <img src="{% if channel.profile.image %}{{ channel.profile.image.url }}
            {% else %}
            {% static 'pics/blank-profile.png'%}
            {% endif %}" alt="" class="channel-pic">
            <div class="channel-name">
                <div>{{channel.username}}</div>
                <p>@{{channel.username}} . {{channel.profile.users_subscribed_cnt}} 
                    {% if  channel.profile.users_subscribed_cnt != 1  %}
                        Subscribers
                    {% else %}
                        Subscriber
                    {% endif %}
                   . {{channel.video_set.count}} 
                   {% if  channel.video_set.count != 1  %}
                        Videos
                    {% else %}
                        Videos
                    {% endif %}
                </p>
                <p class="bio">
                    {% if channel.profile.bio %}
                        {{channel.profile.bio}}
                    {% endif %}
                </p>
                {% if channel != request.user %}
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="video_id" value="subscribe">
                        <input type="hidden" name="subscribe" value="{{channel.id}}">
                        <button class="butn subscribe" onclick="toggleSub()" style="{% if request.user.profile in channel.profile.users_subscribed %}background-color: #888888;{% endif %}">
                            {% if request.user.profile in channel.profile.users_subscribed %}
                                Subscribed
                            {% else %}
                                Subscribe
                            {% endif %}
                        </button>
                    </form>
                {% else %}
                    <a href="{% url 'edit_profile' %}">
                        <button class="butn edit">
                            Edit
                        </button>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock heading %}

{% block video-part %}

{% if videos %}
{% for video in videos %}
    <a href="{% url 'video_view' video.id%}">
        <div class="video">
            <div class="video__thumbnail">
                <img src="{{video.thumbnail.url}}" alt="" />
            </div>
            <div class="video__details">
                <div class="author">
                <img src="{% if video.user.profile.image %}{{ video.user.profile.image.url }}
                {% else %}
                {% static 'pics/blank-profile.png'%}
                {% endif %}" alt="" />
                </div>
                <div class="title">
                <h3>
                    {{video.title}}
                </h3>
                <a href="">{{video.user}}</a>
                <span>{{video.views}} Views • {{ video.upload_date|timesince:""}} Ago</span>
                </div>
            </div>
        </div>
    </a>
{% endfor %}
{% else %}
<div style="text-align: center;" >Haven't Uploaded any Videos.</div>
{% endif %}


{% endblock video-part %}

youtubeProject/Youtube/templates/edit_profile.html
<!-- edit_profile.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
        }

        .container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-top: 50px;
        }

        h2 {
            color: #333;
        }

        label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
            color: #555;
        }

        input, textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            background-color: #ff0000;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Edit Profile</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <label for="{{ form.background_img.id_for_label }}">Background Image</label>
            {{ form.background_img }}
            
            <label for="{{ form.image.id_for_label }}">Profile Picture</label>
            {{ form.image }}
            
            <label for="{{ form.bio.id_for_label }}">Bio</label>
            {{ form.bio }}
            
            <button type="submit">Save Changes</button>
        </form>
    </div>
</body>
</html>

youtubeProject/Youtube/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
</head>
<body>
    <div class="header">
        <div class="header__left">
          <i id="menu" class="material-icons">menu</i>
          <img
            src="https://cdn.mos.cms.futurecdn.net/8gzcr6RpGStvZFA2qRt4v6.jpg"
            alt=""
          />
        </div>
  
        <div class="header__search">
          <form action="">
            <input type="text" placeholder="Search" />
            <button><i class="material-icons">search</i></button>
          </form>
        </div>
  
        <div class="header__icons">
          <i class="material-icons display-this">search</i>
          <i class="material-icons">videocam</i>
          <i class="material-icons">apps</i>
          <i class="material-icons">notifications</i>
          <i class="material-icons display-this">account_circle</i>
        </div>
      </div>
</body>
</html>

youtubeProject/Youtube/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Youtube
{% endblock title %}

{% block body %}

  <div class="videos__container">
    {% for x in videos %}
        {% for y in videos %}
          {% for video in videos %}
            <a href="{% url 'video_view' video.id%}">
              <div class="video">
                <div class="video__thumbnail">
                  <img src="{{video.thumbnail.url}}" alt="" />
                </div>
                <div class="video__details">
                  <div class="author">
                    <img src="{% if video.user.profile.image %}{{ video.user.profile.image.url }}
                    {% else %}
                    {% static 'pics/blank-profile.png'%}
                    {% endif %}" alt="" />
                  </div>
                  <div class="title">
                    <h3>
                      {{video.title}}
                    </h3>
                    <a href="">{{video.user}}</a>
                    <span>{{video.views}} Views • {{ video.upload_date|timesince:""}} Ago</span>
                  </div>
                </div>
              </div>
            </a>
          {% endfor %}
      {% endfor %}
    {% endfor %}
  </div>    

    <!-- <div>This is Home page</div>

    {% if user.username %}
    <p>The logged in user is {{user}}</p>
    <p>The logged in user email is {{user.email}}</p>

    {%else%}
    <p>Non-logged in user</p>
    {% endif %} -->

  <!-- {% if user.is_authenticated %}
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
  {% endif %} -->

    
{% endblock body %}

youtubeProject/Youtube/templates/liked_videos.html
{% extends 'home.html' %}

{% load static %}


{% block head %}
    <style>
        .videos{
            display: flex;
        }
        .video:hover{
            transform: none;
            transition: none;
        }
    </style>
{% endblock head %}

{% block body %}
    {% if liked_videos %}
    {% for video in liked_videos %}
        <a href="{% url 'video_view' video.id%}">
            <div class="video">
                <div class="video__thumbnail">
                    <img src="{{video.thumbnail.url}}" alt="" />
                </div>
                <div class="video__details">
                    <div class="author">
                    <img src="{% if video.user.profile.image %}{{ video.user.profile.image.url }}
                    {% else %}
                    {% static 'pics/blank-profile.png'%}
                    {% endif %}" alt="" />
                    </div>
                    <div class="title">
                    <h3>
                        {{video.title}}
                    </h3>
                    <a href="">{{video.user}}</a>
                    <span>{{video.views}} Views • {{ video.upload_date|timesince:""}} Ago</span>
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}
    {% else %}
    <div style="text-align: center;" >Haven't liked any videos yet.</div>
    {% endif %}
{% endblock body %}

youtubeProject/Youtube/templates/login.html
 {% load static %} 
 <!DOCTYPE html>
 <html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
 </head>
 <body>
    
     
     <!-- <div class="main">
         <h2>Login</h2>
         <form method="post">
             <input type="hidden" name="csrfmiddlewaretoken"
                 value="ceypALmBexJ0VkqL18ez0GC2x0j00SM4GWIKOAzXyRw05r2o7ShYjwoljdhPUvhx">
             <p>
                 <label for="id_username">Username:</label>
                 <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username"
                     maxlength="150" required="" id="id_username">
             </p>
             <p>
                 <label for="id_password">Password:</label>
                 <input type="password" name="password" autocomplete="current-password" required="" id="id_password">
             </p>
             <button type="submit">Login</button>
         </form>
     </div> -->
     
     <div class="main">
         <img src="https://i0.wp.com/www.freefonts.io/wp-content/uploads/2021/08/Youtube-Logo-Font.jpg?resize=849%2C395&ssl=1" alt="YouTube logo">
         <h2>Login</h2>
         <form method="post">
             {% csrf_token %} {{ form.as_p }}
             <button type="submit">Login</button>
         </form>
         <div class="link-register">
             <p>Don't have an account?<br> <a href="{% url 'register' %}">Register here</a>.</p>
         </div>
         </div>
     </div>
 </body>
 </html>